// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urwsiekwgabghowblpix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyd3NpZWt3Z2FiZ2hvd2JscGl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3ODA1OTAsImV4cCI6MjA3ODM1NjU5MH0.o4s4N-BcXGJRhNs0DtyDKCu7IqbgXsA321slsNdpRt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});